version: "3.9"
services:
  # weather_app-proxy:
  #   container_name: weather_app-proxy
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   networks:
  #     - weather_app-net
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - weather_app-back
      # - weather_app-ts
  # weather_app-ts:
  #   container_name: weather_app-ts
  #   build:
  #     context: ../weather_app-ts/.
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     # - "8443:8443"
  #     - "8080:8080"
  #   volumes:
  #     - ../weather_app-ts:/app
  #   depends_on:
  #     - weather_app-back
  #   networks:
  #     - weather_app-net
  #   environment:
  #     - NODE_ENV=development
  #     - PROJECT=localDocker
  #     - HTTPS=false
  #     - PORT=8080
  #   command: ["npm", "run", "start-in-docker"]

  weather_app:
    container_name: weather_app
    build:
      context: ../weather_app/.
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../weather_app:/app
    depends_on:
      - weather_app-redis
      - weather_app-postgres
    networks:
      - weather_app-net
    env_file:
      - ../weather_app/Dockerenv.dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@weather_app-postgres:5432/weather_app_development?pool=6
      - TEST_DATABASE_URL=postgres://postgres:postgres@weather_app-postgres:5432/weather_app_test?pool=6
      - REDIS_URL=redis://weather_app-redis:6379
      - REDIS_DB=0
    command: ["/bin/sh", "-c", "rm -f /app/tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"]

  weather_app-redis:
    image: redis:alpine
    container_name: weather_app-redis
    volumes:
      - weather_app-redis-data:/data
    networks:
      - weather_app-net

  weather_app-postgres:
    image: postgres:12
    container_name: weather_app-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - weather_app-postgres-data:/var/lib/postgresql/data
    networks:
      - weather_app-net

volumes:
  weather_app-redis-data:
  weather_app-postgres-data:

networks:
  weather_app-net:
